version: "3.5"

services:
  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/application
    ports:
      - '8083:80'
    depends_on:
      - php-fpm
    tty: true

  php-fpm:
      build: ./docker/php
      working_dir: /application
      volumes:
          - ./:/application
          - ./docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      ports:
          - '9000'
      links:
          - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app
    ports:
      - '5432:5432'
